#!/bin/bash


if [[ $# -ne 3 ]] && [[ $# -ne 4 ]]; then
    echo "[ERROR] Wrong inputs."
    echo "[INFO]  Usage: gen-tag <tag basename> <original file> <target file> <line number(optional)>"
    exit 1
fi

basename=$1
originalFilename=$2; 
targetFilename=$3

originalFilename=${originalFilename/#~/$HOME}
originalFilename=${originalFilename/#./$PWD}

targetFilename=${targetFilename/#~/$HOME}
targetFilename=${targetFilename/#./$PWD}


if [[ $# -eq 3 ]]; then
    linenumber=1
else
    linenumber=$4
fi

code=$(echo "${basename}${filename}${linenumber}" | shasum | cut -f 1 -d " ")
tag=${basename}-${code}
outputFilename="/Users/Ruikun/workspace/Programs/vimutils/bashtools/my-tags.tag"

echo "[INFO] Tag generated is: ${tag}"
echo "[INFO] Writing tag data to ${outputFilename}"

touch ${outputFilename}

echo -e "${tag}\t${targetFilename}\t${linenumber};\"generated by ${originalFilename}" >> ${outputFilename}









